version: "3.8"

x-common-variables: &common-variables
  MYSQL_DATABASE: whist

  MYSQL_PASSWORD: MYSQL_ROOT_PASSWORD

services:
  mysql_db:
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.6
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: "%"

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    container_name: node
    build:
      dockerfile: Dockerfile.dev
      context: "./whist_be"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./whist_be:/app
    environment:
      <<: *common-variables
      DB_USER: root
      DB_HOST: mysql_db
      DB_PW: MYSQL_ROOT_PASSWORD
      DB_PORT: "3306"
      PORT: "4000"
      HOST: "0.0.0.0"
    ports:
      - "4000:4000"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./whist
    volumes:
      - /app/node_modules
      - ./whist:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
